version: '3.0'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TestDb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  # app:
  #   image: csv_parser
  #   container_name: nodejs
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
